Controllers/BillsController.cs
using CoffeeShopManagment.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;

namespace CoffeeShopManagment.Controllers
{
    [CheckAccess]
    public class BillsController : Controller
    {
        private IConfiguration configuration;

        public BillsController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }
        #region BillList
        public IActionResult Index()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                SqlCommand sqlCommand = connection.CreateCommand();
                sqlCommand.CommandType = CommandType.StoredProcedure;
                sqlCommand.CommandText = "PR_Bills_SelectAll";
                SqlDataReader reader = sqlCommand.ExecuteReader();
                DataTable dataTable = new DataTable();
                dataTable.Load(reader);
                return View(dataTable);
            }
        }
        #endregion

        #region BillForm
        public IActionResult Form(int? BillID)
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            List<UserDropDownModel> userList = new List<UserDropDownModel>();
            List<OrderDropDownModel> orderList = new List<OrderDropDownModel>();

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                // Load User Dropdown
                using (SqlCommand command = connection.CreateCommand())
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.CommandText = "PR_User_DropDown";
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        DataTable dataTable = new DataTable();
                        dataTable.Load(reader);
                        foreach (DataRow data in dataTable.Rows)
                        {
                            UserDropDownModel userDropDownModel = new UserDropDownModel
                            {
                                UserID = Convert.ToInt32(data["UserID"]),
                                UserName = data["UserName"].ToString()
                            };
                            userList.Add(userDropDownModel);
                        }
                    }
                }

                // Load Order Dropdown
                using (SqlCommand command = connection.CreateCommand())
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.CommandText = "PR_Order_DropDown";
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        DataTable dataTable = new DataTable();
                        dataTable.Load(reader);
                        foreach (DataRow data in dataTable.Rows)
                        {
                            OrderDropDownModel orderDropDownModel = new OrderDropDownModel
                            {
                                OrderID = Convert.ToInt32(data["OrderID"])
                            };
                            orderList.Add(orderDropDownModel);
                        }
                    }
                }

                BillsModel billsModel = null;
                if (BillID.HasValue)
                {
                    using (SqlCommand command = connection.CreateCommand())
                    {
                        command.CommandType = CommandType.StoredProcedure;
                        command.CommandText = "PR_Bills_SelectByPK";
                        command.Parameters.Add("@BillID", SqlDbType.Int).Value = BillID.Value;
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            if (reader.Read())
                            {
                                billsModel = new BillsModel
                                {
                                    BillID = Convert.ToInt32(reader["BillID"]),
                                    BillNumber = reader["BillNumber"].ToString(),
                                    BillDate = Convert.ToDateTime(reader["BillDate"]),
                                    OrderID = Convert.ToInt32(reader["OrderID"]),
                                    TotalAmount = Convert.ToDecimal(reader["TotalAmount"]),
                                    Discount = Convert.ToDecimal(reader["Discount"]),
                                    NetAmount = Convert.ToDecimal(reader["NetAmount"]),
                                    UserID = Convert.ToInt32(reader["UserID"])
                                };
                            }
                        }
                    }
                }

                // Pass dropdowns and model to View
                ViewBag.UserList = userList.Count > 0 ? userList : new List<UserDropDownModel>();
                ViewBag.OrderList = orderList.Count > 0 ? orderList : new List<OrderDropDownModel>();

                return View("Form", billsModel);
            }
        }
        #endregion

        #region BillSave
        public IActionResult BillSave(BillsModel model)
        {
            //if (ModelState.IsValid)
            //{
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                if (model.BillID == 0)
                {
                    command.CommandText = "PR_Bills_Insert";
                }
                else
                {
                    command.CommandText = "PR_Bills_Update";
                    command.Parameters.Add("@BillID", SqlDbType.Int).Value = model.BillID;
                }
                command.Parameters.Add("@BillNumber", SqlDbType.VarChar).Value = model.BillNumber;
                command.Parameters.Add("@BillDate", SqlDbType.DateTime).Value = model.BillDate;
                command.Parameters.Add("@OrderID", SqlDbType.Int).Value = model.OrderID;
                command.Parameters.Add("@TotalAmount", SqlDbType.Decimal).Value = model.TotalAmount;
                command.Parameters.Add("@Discount", SqlDbType.Decimal).Value = model.Discount;
                command.Parameters.Add("@NetAmount", SqlDbType.Decimal).Value = model.NetAmount;
                command.Parameters.Add("@UserID", SqlDbType.Int).Value = model.UserID;
                command.ExecuteNonQuery();
                return RedirectToAction("Index");
            }
            //}

            // Reload dropdowns if ModelState is not valid
            LoadDropdowns();
            return View("Form", model);
        }
        #endregion

        #region BillDelete
        public IActionResult BillDelete(int BillID)
        {
            try
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    SqlCommand command = connection.CreateCommand();
                    command.CommandType = CommandType.StoredProcedure;
                    command.CommandText = "PR_Bills_Delete";
                    command.Parameters.Add("@BillID", SqlDbType.Int).Value = BillID;
                    command.ExecuteNonQuery();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["Error Message"] = ex.Message;
                return RedirectToAction("Index");
            }
        }
        #endregion

        #region DropDowns
        private void LoadDropdowns()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                // Load User Dropdown
                using (SqlCommand command = connection.CreateCommand())
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.CommandText = "PR_User_DropDown";
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        DataTable dataTable = new DataTable();
                        dataTable.Load(reader);
                        List<UserDropDownModel> userList = new List<UserDropDownModel>();
                        foreach (DataRow data in dataTable.Rows)
                        {
                            UserDropDownModel userDropDownModel = new UserDropDownModel
                            {
                                UserID = Convert.ToInt32(data["UserID"]),
                                UserName = data["UserName"].ToString()
                            };
                            userList.Add(userDropDownModel);
                        }
                        ViewBag.UserList = userList.Count > 0 ? userList : new List<UserDropDownModel>();  // Initialize the list if empty
                    }
                }

                // Load Order Dropdown
                using (SqlCommand command = connection.CreateCommand())
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.CommandText = "PR_Order_DropDown";

Controllers/CityController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using CoffeeShopManagment.Models;

namespace CoffeeShopManagment.Controllers
{
    public class CityController : Controller
    {
        private readonly IConfiguration _configuration;

        #region configuration
        public CityController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        #endregion

        #region Index
        public IActionResult Index()
        {
            string connectionstr = this._configuration.GetConnectionString("ConnectionString");
            //PrePare a connection
            DataTable dt = new DataTable();
            SqlConnection conn = new SqlConnection(connectionstr);
            conn.Open();

            //Prepare a Command
            SqlCommand objCmd = conn.CreateCommand();
            objCmd.CommandType = CommandType.StoredProcedure;
            objCmd.CommandText = "PR_LOC_City_SelectAll";

            SqlDataReader objSDR = objCmd.ExecuteReader();
            dt.Load(objSDR);
            conn.Close();
            return View("Index", dt);
        }
        #endregion

        #region Delete
        public IActionResult Delete(int CityID)
        {
            string connectionstr = _configuration.GetConnectionString("ConnectionString");
            using (SqlConnection conn = new SqlConnection(connectionstr))
            {
                conn.Open();
                using (SqlCommand sqlCommand = conn.CreateCommand())
                {
                    sqlCommand.CommandType = CommandType.StoredProcedure;
                    sqlCommand.CommandText = "PR_LOC_City_Delete";
                    sqlCommand.Parameters.AddWithValue("@CityID", CityID);
                    sqlCommand.ExecuteNonQuery();
                }
            }
            return RedirectToAction("Index");
        }
        #endregion
    }
}

Controllers/EmailController.cs
using CoffeeShopManagment.Services;
using Microsoft.AspNetCore.Mvc;

namespace CoffeeShopManagment.Controllers
{
    [CheckAccess]
    public class EmailController : Controller
    {
        private readonly IEmailSender _emailSender;

        public EmailController(IEmailSender emailSender)
        {
            _emailSender = emailSender;
        }

        [HttpPost]
        public async Task<IActionResult> SendEmail(string toEmail, string subject, string body)
        {
            await _emailSender.SendEmailAsync(toEmail, subject, body);
            TempData["Success"] = "Email sent successfully!";
            return RedirectToAction("Index");
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/StateController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using CoffeeShopManagment.Models;

namespace CoffeeShopManagment.Controllers
{
    public class StateController : Controller
    {
        private readonly IConfiguration _configuration;

        #region configuration
        public StateController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        #endregion

        #region Index
        public IActionResult Index()
        {
            string connectionstr = _configuration.GetConnectionString("ConnectionString");
            DataTable dt = new DataTable();
            using (SqlConnection conn = new SqlConnection(connectionstr))
            {
                conn.Open();
                using (SqlCommand objCmd = conn.CreateCommand())
                {
                    objCmd.CommandType = CommandType.StoredProcedure;
                    objCmd.CommandText = "PR_LOC_State_SelectAll";
                    SqlDataReader objSDR = objCmd.ExecuteReader();
                    dt.Load(objSDR);
                }
            }
            return View("Index", dt);
        }
        #endregion

        #region Delete
        public IActionResult Delete(int StateID)
        {
            string connectionstr = _configuration.GetConnectionString("ConnectionString");
            using (SqlConnection conn = new SqlConnection(connectionstr))
            {
                conn.Open();
                using (SqlCommand sqlCommand = conn.CreateCommand())
                {
                    sqlCommand.CommandType = CommandType.StoredProcedure;
                    sqlCommand.CommandText = "PR_LOC_State_Delete";
                    sqlCommand.Parameters.AddWithValue("@StateID", StateID);
                    sqlCommand.ExecuteNonQuery();
                }
            }
            return RedirectToAction("Index");
        }
        #endregion
    }
}

Views/Shared/_Layout.cshtml
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>@ViewData["Title"] - Dashboard - NiceAdmin Bootstrap Template</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Bootstrap Icons -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CoffeeShopManagment.styles.css" asp-append-version="true" />
</head>
<body>
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="d-flex align-items-center justify-content-between">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="logo d-flex align-items-center">
                <img src="~/assets/img/logo.png" alt="">
                <span class="d-none d-lg-block">CoffeeShop</span>
            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div><!-- End Logo -->

        <div class="search-bar">
            <form class="search-form d-flex align-items-center" method="POST" action="#">
                <input type="text" name="query" placeholder="Search" title="Enter search keyword">
                <button type="submit" title="Search"><i class="bi bi-search"></i></button>
            </form>
        </div><!-- End Search Bar -->

        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">

                <li class="nav-item d-block d-lg-none">
                    <a class="nav-link nav-icon search-bar-toggle " href="#">
                        <i class="bi bi-search"></i>
                    </a>
                </li><!-- End Search Icon-->    

                <li class="nav-item dropdown pe-3">
                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <img src="~/assets/img/profile-img.jpg" alt="Profile" class="rounded-circle">
                        <span class="d-none d-md-block dropdown-toggle ps-2">@CommonVariable.UserName()</span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                    </a><!-- End Profile Iamge Icon -->
                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                        <li class="dropdown-header">
                            <h6>Kevin Anderson</h6>
                            <span>Web Designer</span>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" asp-area="" asp-controller="Home" asp-action="Profile">
                                <i class="bi bi-person"></i>
                                <span>My Profile</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" asp-area="" asp-controller="Home" asp-action="Profile">
                                <i class="bi bi-gear"></i>
                                <span>Account Settings</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" asp-area="" asp-controller="Home" asp-action="FAQ">
                                <i class="bi bi-question-circle"></i>
                                <span>Need Help?</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="#">
                                <i class="bi bi-box-arrow-right"></i>
                                <span>Sign Out</span>
                            </a>
                        </li>

                    </ul><!-- End Profile Dropdown Items -->
                </li><!-- End Profile Nav -->

            </ul>
        </nav><!-- End Icons Navigation -->

    </header><!-- End Header -->
    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">
            <li class="nav-heading">Tables</li>

            <li class="nav-item">
                <a class="nav-link " asp-controller="Home" asp-action="Index">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="" asp-controller="Product" asp-action="Index">
                    <i class="bi bi-card-list"></i>
                    <span>Product Table</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="" asp-controller="User" asp-action="Index">
                    <i class="bi bi-card-list"></i>
                    <span>User Table</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="" asp-controller="Order" asp-action="Index">
                    <i class="bi bi-card-list"></i>
                    <span>Order Table</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="" asp-controller="OrderDetail" asp-action="Index">
                    <i class="bi bi-card-list"></i>
                    <span>Order Detail Table</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="" asp-controller="Bills" asp-action="Index">
                    <i class="bi bi-card-list"></i>
                    <span>Bills Table</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="" asp-controller="Customer" asp-action="Index">
                    <i class="bi bi-card-list"></i>
                    <span>Customer Table</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="" asp-controller="City" asp-action="Index">
                    <i class="bi bi-card-list"></i>
                    <span>City Table</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="" asp-controller="State" asp-action="Index">
                    <i class="bi bi-card-list"></i>
                    <span>State Table</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="" asp-controller="Country" asp-action="Index">
                    <i class="bi bi-card-list"></i>
                    <span>Country Table</span>
                </a>
            </li>
            @* <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Email" asp-action="Index">
                    <i class="bi bi-envelope"></i>
                    Send Email
                </a>
            </li> *@


        </ul>

    </aside><!-- End Sidebar-->


    <main id="main" class="main">
        @RenderBody()
    </main>

    @* <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
        <div class="copyright">
            &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
    </footer><!-- End Footer --> *@

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
    
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/chart.js/chart.umd.js"></script>
    <script src="~/assets/vendor/echarts/echarts.min.js"></script>
    <script src="~/assets/vendor/quill/quill.js"></script>
    <script src="~/assets/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="~/assets/vendor/tinymce/tinymce.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>
    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)

    <a asp-area="" asp-controller="Email" asp-action="Index" id="email-button" class="floating-button" title="Send Email">
        <i class="bi bi-envelope"></i>
    </a>
    @* <a class="floating-button" asp-controller="User" asp-action="Logout"><i class="bi bi-box-arrow-right"></i></a> *@

</body>
</html>

Views/Shared/_Layout_Login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Pages / Login - NiceAdmin Bootstrap Template</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/img/favicon.png" rel="icon">
    <link href="~/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <!-- Vendor CSS Files -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/vendor/simple-datatables/style.css" rel="stylesheet">
    <!-- Template Main CSS File -->
    <link href="~/css/style.css" rel="stylesheet">
    <!-- =======================================================
    * Template Name: NiceAdmin
    * Updated: May 30 2023 with Bootstrap v5.3.0
    * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>
<body>
    @RenderBody()
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/chart.js/chart.umd.js"></script>
    <script src="~/vendor/echarts/echarts.min.js"></script>
    <script src="~/vendor/quill/quill.min.js"></script>
    <script src="~/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="~/vendor/tinymce/tinymce.min.js"></script>
    <script src="~/vendor/php-email-form/validate.js"></script>
    <!-- Template Main JS File -->
    <script src="~/js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout_Register.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Pages / Login - NiceAdmin Bootstrap Template</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: NiceAdmin
    * Updated: May 30 2023 with Bootstrap v5.3.0
    * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>
<body>
    @RenderBody()

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/chart.js/chart.umd.js"></script>
    <script src="~/assets/vendor/echarts/echarts.min.js"></script>
    <script src="~/assets/vendor/quill/quill.min.js"></script>
    <script src="~/assets/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="~/assets/vendor/tinymce/tinymce.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>
    <script src="~/assets/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/assets/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>