Controllers/OrderDetailController.cs
using CoffeeShopManagment.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;

namespace CoffeeShopManagment.Controllers
{
    [CheckAccess]
    public class OrderDetailController : Controller
    {
        private IConfiguration configuration;

        public OrderDetailController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }
        #region OrderDetailList
        public IActionResult Index()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand sqlCommand = connection.CreateCommand();
            sqlCommand.CommandType = System.Data.CommandType.StoredProcedure;
            sqlCommand.CommandText = "PR_OrderDetail_SelectAll";
            SqlDataReader reader = sqlCommand.ExecuteReader();
            DataTable dataTable = new DataTable();
            dataTable.Load(reader);
            return View(dataTable);
        }
        #endregion
        #region ODForm
        public IActionResult Form(int OrderDetailID)
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection2 = new SqlConnection(connectionString);
            connection2.Open();
            SqlCommand command2 = connection2.CreateCommand();
            command2.CommandType = System.Data.CommandType.StoredProcedure;
            command2.CommandText = "PR_User_DropDown";
            SqlDataReader reader2 = command2.ExecuteReader();
            DataTable dataTable2 = new DataTable();
            dataTable2.Load(reader2);
            List<UserDropDownModel> userList = new List<UserDropDownModel>();
            foreach (DataRow data in dataTable2.Rows)
            {
                UserDropDownModel userDropDownModel = new UserDropDownModel();
                userDropDownModel.UserID = Convert.ToInt32(data["UserID"]);
                userDropDownModel.UserName = data["UserName"].ToString();
                userList.Add(userDropDownModel);
            }
            ViewBag.UserList = userList;

            SqlConnection connection1 = new SqlConnection(connectionString);
            connection1.Open();
            SqlCommand command1 = connection1.CreateCommand();
            command1.CommandType = System.Data.CommandType.StoredProcedure;
            command1.CommandText = "PR_Order_DropDown";
            SqlDataReader reader1 = command1.ExecuteReader();
            DataTable dataTable1 = new DataTable();
            dataTable1.Load(reader1);
            List<OrderDropDownModel> orderList = new List<OrderDropDownModel>();
            foreach (DataRow data in dataTable1.Rows)
            {
                OrderDropDownModel orderDropDownModel = new OrderDropDownModel();
                orderDropDownModel.OrderID = Convert.ToInt32(data["OrderID"]);
                orderList.Add(orderDropDownModel);
            }
            ViewBag.OrderList = orderList;

            SqlConnection connection3 = new SqlConnection(connectionString);
            connection3.Open();
            SqlCommand command3 = connection3.CreateCommand();
            command3.CommandType = System.Data.CommandType.StoredProcedure;
            command3.CommandText = "PR_Product_DropDown";
            SqlDataReader reader3 = command3.ExecuteReader();
            DataTable dataTable3 = new DataTable();
            dataTable3.Load(reader3);
            List<ProductDropDownModel> productList = new List<ProductDropDownModel>();
            foreach (DataRow data in dataTable3.Rows)
            {
                ProductDropDownModel productDropDownModel = new ProductDropDownModel();
                productDropDownModel.ProductID = Convert.ToInt32(data["ProductID"]);
                productDropDownModel.ProductName = data["ProductName"].ToString();
                productList.Add(productDropDownModel);
            }
            ViewBag.ProductList = productList;

            #region OrderDetailByID

            SqlConnection connection4 = new SqlConnection(connectionString);
            connection4.Open();
            SqlCommand command4 = connection4.CreateCommand();
            command4.CommandType = CommandType.StoredProcedure;
            command4.CommandText = "PR_OrderDetail_SelectByPK";
            command4.Parameters.AddWithValue("@OrderDetailID", OrderDetailID);
            SqlDataReader reader4 = command4.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader4);
            OrderDetailModel orderDetailModel = new OrderDetailModel();

            foreach (DataRow dataRow in table.Rows)
            {
                orderDetailModel.OrderDetailID = Convert.ToInt32(@dataRow["OrderDetailID"]);
                orderDetailModel.OrderID = Convert.ToInt32(@dataRow["OrderID"]);
                orderDetailModel.ProductID = Convert.ToInt32(@dataRow["ProductID"]);
                orderDetailModel.Quantity = Convert.ToInt32(@dataRow["Quantity"]);
                orderDetailModel.Amount = Convert.ToDecimal(@dataRow["Amount"]);
                orderDetailModel.TotalAmount = Convert.ToDecimal(@dataRow["TotalAmount"]);
                orderDetailModel.UserID = Convert.ToInt32(@dataRow["UserID"]);
            }

            #endregion

            return View("Form", orderDetailModel);
        }
        #endregion
        #region ODSave
        public IActionResult OrderDetailSave(OrderDetailModel orderDetailModel)
        {
            if (orderDetailModel.OrderID <= 0)
            {
                ModelState.AddModelError("OrderID", "A valid Order is requried.");
            }
            if (orderDetailModel.UserID <= 0)
            {
                ModelState.AddModelError("UserID", "A valid User is requried.");
            }
            if (orderDetailModel.ProductID <= 0)
            {
                ModelState.AddModelError("ProductID", "A valid Product is requried.");
            }
            if (ModelState.IsValid)
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                if (orderDetailModel.OrderDetailID == 0)
                {
                    command.CommandText = "PR_OrderDetail_Insert";
                }
                else
                {
                    command.CommandText = "PR_OrderDetail_Update";
                    command.Parameters.Add("@OrderDetailID", SqlDbType.Int).Value = orderDetailModel.OrderDetailID;
                }
                command.Parameters.Add("@OrderID", SqlDbType.Int).Value = orderDetailModel.OrderID;
                command.Parameters.Add("@ProductID", SqlDbType.Int).Value = orderDetailModel.ProductID;
                command.Parameters.Add("@Quantity", SqlDbType.Int).Value = orderDetailModel.Quantity;
                command.Parameters.Add("@Amount", SqlDbType.Decimal).Value = orderDetailModel.Amount;
                command.Parameters.Add("@TotalAmount", SqlDbType.Decimal).Value = orderDetailModel.TotalAmount;
                command.Parameters.Add("@UserID", SqlDbType.Int).Value = orderDetailModel.UserID;
                command.ExecuteNonQuery();
                return RedirectToAction("Index");
            }
            return View("Form", orderDetailModel);
        }
        #endregion

        #region ODDelete
        public IActionResult OrderDetailDelete(int OrderDetailID)
        {
            try
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                command.CommandText = "PR_OrderDetail_Delete";
                command.Parameters.Add("@OrderDetailID", SqlDbType.Int).Value = OrderDetailID;
                command.ExecuteNonQuery();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["Error Message"] = ex.Message;
                return RedirectToAction("Index");
            }

        }
        #endregion
    }
}

Views/OrderDetail/Form.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model CoffeeShopManagment.Models.OrderDetailModel
<div class="container">

    <section class="section">
        <div class="row">
            <div class="col">

                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Order Details</h5>
                        <form asp-controller="OrderDetail" asp-action="OrderDetailSave" method="post">
                            @Html.HiddenFor(x => x.OrderDetailID)


                            <div class="row mb-3">
                                <label asp-for="OrderID" class="col-sm-2 col-form-label">Order ID</label>
                                <div class="col-sm-10">
                                    <select asp-for="OrderID" class="form-control" asp-items="@(new SelectList(ViewBag.OrderList, "OrderID", "OrderID"))">
                                        <option value="">Select Order ID</option>
                                    </select>
                                    <span asp-validation-for="OrderID" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label asp-for="ProductID" class="col-sm-2 col-form-label">Product Name</label>
                                <div class="col-sm-10">
                                    <select asp-for="ProductID" class="form-control" asp-items="@(new SelectList(ViewBag.ProductList, "ProductID", "ProductName"))">
                                        <option value="">Select Product</option>
                                    </select>
                                    <span asp-validation-for="ProductID" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label asp-for="Quantity" for="inputText" class="col-sm-2 col-form-label">Quantity</label>
                                <div class="col-sm-10">
                                    <input asp-for="Quantity" type="number" class="form-control">
                                    <span asp-validation-for="Quantity" class="text-danger"></span>

                                </div>
                            </div>
                            <div class="row mb-3">
                                <label asp-for="Amount" for="inputText" class="col-sm-2 col-form-label">Amount</label>
                                <div class="col-sm-10">
                                    <input asp-for="Amount" type="number" class="form-control">
                                    <span asp-validation-for="Amount" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label asp-for="TotalAmount" for="inputText" class="col-sm-2 col-form-label">Total Amount</label>
                                <div class="col-sm-10">
                                    <input asp-for="TotalAmount" type="number" class="form-control">
                                    <span asp-validation-for="TotalAmount" class="text-danger"></span>

                                </div>
                            </div>
                            <div class="row mb-3">
                                <label asp-for="UserID" class="col-sm-2 col-form-label">User Name</label>
                                <div class="col-sm-10">
                                    <select class="form-control" asp-for="UserID" asp-items="@(new SelectList(ViewBag.UserList, "UserID", "UserName"))">
                                        <option value="">Select User</option>
                                    </select>
                                    <span asp-validation-for="UserID" class="text-danger"></span>

                                </div>
                            </div>

                            <div class="row mb-3">
                                <div class="col-sm-10">
                                    <button type="submit" class="btn btn-primary">Submit Form</button>
                                </div>
                            </div>

                        </form>

                    </div>
                </div>

            </div>


        </div>
    </section>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/OrderDetail/Index.cshtml
@model DataTable;
@using System.Data

<div class="d-flex justify-content-between align-items-center mb-3">
    <div></div> <!-- Placeholder for flex alignment -->
    <a class="btn btn-primary" asp-area="" asp-controller="OrderDetail" asp-action="Form">
        <i class="bi bi-plus-lg"></i> Add
    </a>
</div>

<h6 class="text-danger">@TempData["Error Message"]</h6>

<table class="table">
    <thead>
        <tr>
            <th>OrderDetailID</th>
            <th>OrderID</th>
            <th>ProductID</th>
            <th>Quantity</th>
            <th>Amount</th>
            <th>Total Amount</th>
            <th>UserID</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (DataRow dataRow in Model.Rows)
        {
            <tr>
                <td>@dataRow["OrderDetailID"]</td>
                <td>@dataRow["OrderID"]</td>
                <td>@dataRow["ProductID"]</td>
                <td>@dataRow["Quantity"]</td>
                <td>@dataRow["Amount"]</td>
                <td>@dataRow["TotalAmount"]</td>
                <td>@dataRow["UserID"]</td>
                <td>
                    <div class="d-flex align-items-center">
                        <a asp-area="" asp-controller="OrderDetail" asp-action="Form" asp-route-OrderDetailId="@dataRow["OrderDetailID"]" class="btn btn-outline-warning btn-sm me-2">
                            <i class="bi bi-pencil-square"></i>
                        </a>
                        <form id="deleteForm_@dataRow["OrderDetailID"]" method="post" asp-controller="OrderDetail" asp-action="OrderDetailDelete" class="mb-0">
                            <input type="hidden" name="OrderDetailID" value="@dataRow["OrderDetailID"]" />
                            <button type="button" class="btn btn-outline-danger btn-sm" onclick="confirmDelete('@dataRow["OrderDetailID"]')">
                                <i class="bi bi-trash"></i>
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

<!-- SweetAlert JavaScript -->
<script>
    function confirmDelete(orderDetailId) {
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                document.getElementById('deleteForm_' + orderDetailId).submit();
            }
        });
    }

    document.addEventListener('DOMContentLoaded', function () {
        var errorMessage = '@TempData["Error Message"]';
        if (errorMessage) {
            Swal.fire({
                title: 'Error',
                text: errorMessage,
                icon: 'error',
                confirmButtonColor: '#3085d6'
            });
        }
    });
</script>